# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6832b43d7b371f2113167180fedd50a5e8f0bba1ff1f065689a3f61774419e577e374b644074854f9bb18e7cea45f322af7353d4bdb73784c5f760c95623361

test:
  secret_key_base: 12a3b5f52dad9bea5ad5cd9f65b6a24cf3f2115d6029a2a95a5362592960eacb280e12eccde8c906f5a02d86175740d6f8275b6c87ebf7353e20143e738979d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
